# gorm 反表
base:
  is_dev: false
db_info:
  host: localhost
  port: 3306
  username: root
  password: 123456
  # database: binance
  database: gormtests
  type: 0
  # host: 192.168.99.49
  # port: 3306
  # username: root
  # password: trdrelVmlOKiGGC0OrL8
  # database: binance
  # type: 0
out_dir: ./model_src
url_tag: json
language: 中 文
db_tag: gorm
user_gorm_model: true
simple: false
is_web_tag: true
is_web_tag_pk_hidden: false
is_foreign_key: false
is_out_sql: true
is_out_func: false
is_gui: true
is_table_name: true
is_null_to_point: false
table_prefix: ""
self_type_define:
  datetime: time.Time
  time: time.Time
  date: time.Time
out_file_name: ""
web_tag_type: 0 # json 小驼峰
table_names: ""
is_column_name: true
is_out_file_by_table_name: true
is_out_page: true
